version: "3.9"

services:
  db:
    image: postgres:16
    container_name: helpmeoil_db
    restart: always
    environment:
      POSTGRES_USER: helpmeoil
      POSTGRES_PASSWORD: helpmeoil_pass
      POSTGRES_DB: helpmeoil_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - helpmeoil_network

  adminer:
    image: adminer
    container_name: helpmeoil_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - helpmeoil_network

volumes:
  postgres_data:

networks:
  helpmeoil_network:
